version: "3.9"

services:
  backpack:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/code
    ports:
    - "8001:8000"
    restart: unless-stopped
  #backpack-s2:
  #  build: .
  #  command: python manage.py runserver 0.0.0.0:8000
  #  volumes:
  #    - .:/code
  #  ports:
  #    - "8002:8000"
  #  restart: unless-stopped
  #backpack-s3:
  #  build: .
  #  command: python manage.py runserver 0.0.0.0:8000
  #  volumes:
  #    - .:/code
  #  ports:
  #    - "8003:8000"
  #  restart: unless-stopped
  nginx:
    image: library/nginx:latest
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8080:80"
    restart: unless-stopped
    depends_on:
      - backpack
      #- backpack-s2
      #- backpack-s3

networks:
  default:
    driver: bridge